### ISSUE TITLE
將 `ProjectVersion.txt` 加入版本追蹤

### ISSUE THREAD

**Issue by chikacc** [L1247/rStarUtility#1]
## 問題描述

目前在 `.gitignore` 中，將 `ProjectSettings/ProjectVersion.txt` 被設為忽略追蹤。
在全新 clone 下來的專案中，將會遺失專案的 Unity 版本訊息，開啟時即使用對應專案的版本，仍會顯示專案版本 `before 5.0` 並詢問是否變更版本。
缺少 `ProjectVersion.txt` 並不會影響專案開啟，但由於無法得知目前專案所對應的版本，涉及多人協作時一定程度上會有影響。

## 解決辦法

在 `.gitignore` 中移除忽略追蹤，並將最新版本的 `ProjectSettings/ProjectVersion.txt` 加入版本控管。

## 螢幕截圖

![螢幕擷取畫面 2022-04-30 202142](https://user-images.githubusercontent.com/13810485/166105625-974b7238-a1fe-4543-9908-967f69cf3940.png)

## 操作環境

作業系統: `Windows 11 21H2`
Unity 版本: `2021.3.1f1`

**Comment by L1247** [comment]
沒錯，的確是有被加入到`.gitignore`
因為`.gitignore`我是用我習慣的檔案直接複製
感謝建議，已修正
