### ISSUE TITLE
新增 `package.json` 使專案能導入至 package manager

### ISSUE THREAD

**Issue by chikacc** [L1247/rStarUtility#2]
## 問題描述

利用 custom package 搭配 package manager 更有效的管理導入的專案，
其他專案可透過 `https://github.com/L1247/rStarUtility.git?path=Assets/rStarUtility` 將套件導入至 package manager。

## 解決辦法

在 `Assets/rStarUtility` 新增 `package.json`，參考如下：

```json
{
    "name": "com.rstar.rstarutility",
    "displayName": "rStar Utility",
    "description": "包含DDD框架的實作以及相關的測試\n包含一些常用的工具庫\n相依Zenject、UniRx、MessagePipe、UniTask",
    "version": "1.0.0",
    "unity": "2021.3",
    "unityRelease": "1f1",
    "dependencies": {},
    "author": {
      "name": "rStar",
      "email": "starlove124760@gmail.com",
      "url": "https://starloveunity.wordpress.com/"
    }
}
```

## 螢幕截圖

![](https://user-images.githubusercontent.com/13810485/166107305-2c74bf85-609b-49d8-94c8-da49be0a8710.png)

## 操作環境

作業系統: `Windows 11 21H2`
Unity 版本: `2021.3.1f1`

**Comment by L1247** [comment]
感謝提供這麼好的更新方式
以前知道但沒特別研究
原來透過`新增 package.json` 就可以達到
