### ISSUE TITLE
新增 Test runner 自動化

### ISSUE THREAD

**Issue by chikacc** [L1247/rStarUtility#5]
## 問題描述

利用 GitHub Actions 可以更有效率地完成自動化測試。

## 解決辦法

推薦使用 [GameCI](https://game.ci)，部分說明文件連結如下：

- [Getting started](https://game.ci/docs/github/getting-started)
- [Activation](https://game.ci/docs/github/activation)
- [Test runner](https://game.ci/docs/github/test-runner)

## 螢幕截圖

![螢幕擷取畫面 2022-05-26 183055](https://user-images.githubusercontent.com/13810485/170472260-3943a9c5-3482-4531-821e-729a61c8cdf3.png)

![螢幕擷取畫面 2022-05-26 183319](https://user-images.githubusercontent.com/13810485/170472359-f3c9fed3-a1b8-4e74-bd48-f8db6f8d64d0.png)

## 操作環境

作業系統: `Windows 11 21H2`
Unity 版本: `2021.3.1f1`

**Comment by L1247** [comment]
好的 我來處理一下，非常謝謝你一直提供可以讓這工具更好的方法
GameCI之前有碰過  還沒在公開專案處理過

**Comment by L1247** [comment]
@chika-chang 請問你是怎麼得到license的呢
我目前遇到serial has reached the maximum number of activations. 
是否需要Pro license 才可以

![2022-05-28_17-44-49](https://user-images.githubusercontent.com/12491092/170820095-9e065244-9be9-4be6-96c3-dca5bbec4547.png)

**Comment by chikacc** [comment]
我是使用 Personal Edition，試試看把所有 Unity Hub 的授權都 Return 再 Activate。

**Comment by L1247** [comment]
呼 可以了
我創新帳號後還是不行
最後用無痕去嘗試就可以下載了
